
'S%   - SPRITE
'X%   - COLUNA
'Y%   - LINHA
'T1%  - TIME
'TY%  - POSIÇÃO TILE Y
'DX%  - INCREMENTO DE 8 PIXELS
'J%   - CONTROLE DO JOGADOR

'JP%  - PULO
'T12% - TIME PULO
'CF%  - TILE PISO 1
'CF2% - TILE PISO 2

'ST%  - LIGA QUEDA
'Q%   - INCREMENTO DA QUEDA
'TQ   - TIME DA QUEDA
'F%   - QDO FOR GAME OVER NA EXIBIÇÃO NÃO VERIFICAR TILES OU PISO

'DX% - INCREMENTO 8 PIXELS NEGATIVO = ESQUERDA / POSITIVO = DIREITA 
'SD% - 1 - SIGA PRA DIREITA
'SE% - 1 - SIGA PARA ESQUERDA

'TQ - CONTROLE TIME DA TOCHA